/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NoDataImport } from './routes/noData'
import { Route as ErrorImport } from './routes/error'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileProfileIdImport } from './routes/profile/$profileId'
import { Route as ProfileProfileIdRepoIdImport } from './routes/profile_.$profileId.$repoId'

// Create/Update Routes

const NoDataRoute = NoDataImport.update({
  path: '/noData',
  getParentRoute: () => rootRoute,
} as any)

const ErrorRoute = ErrorImport.update({
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileProfileIdRoute = ProfileProfileIdImport.update({
  path: '/profile/$profileId',
  getParentRoute: () => rootRoute,
} as any)

const ProfileProfileIdRepoIdRoute = ProfileProfileIdRepoIdImport.update({
  path: '/profile/$profileId/$repoId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/error': {
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/noData': {
      preLoaderRoute: typeof NoDataImport
      parentRoute: typeof rootRoute
    }
    '/profile/$profileId': {
      preLoaderRoute: typeof ProfileProfileIdImport
      parentRoute: typeof rootRoute
    }
    '/profile/$profileId/$repoId': {
      preLoaderRoute: typeof ProfileProfileIdRepoIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ErrorRoute,
  NoDataRoute,
  ProfileProfileIdRoute,
  ProfileProfileIdRepoIdRoute,
])

/* prettier-ignore-end */
